export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST'
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS'
export const SEARCH_DATA_FAILURE = 'SEARCH_DATA_FAILURE'
export const SEARCH_DATA_CLEAR = 'SEARCH_DATA_CLEAR'
